name: openfaas_tp
channels:
- conda-forge
- defaults
dependencies:
- boost=1.70.0=py37h9de70de_1
- boost-cpp=1.70.0=h8e57a91_2
- bzip2=1.0.8=h516909a_2
- cairo=1.16.0=hfb77d84_1002
- fontconfig=2.13.1=h86ecdb6_1001
- freetype=2.10.0=he983fc9_1
- gettext=0.19.8.1=hc5be6a0_1002
- glib=2.58.3=py37h6f030ca_1002
- icu=64.2=he1b5a44_1
- jpeg=9c=h14c3975_1001
- libiconv=1.15=h516909a_1005
- libpng=1.6.37=hed695b0_0
- libtiff=4.1.0=hc3755c2_1
- libuuid=2.32.1=h14c3975_1000
- libxcb=1.13=h14c3975_1002
- libxml2=2.9.10=hee79883_0
- lz4-c=1.8.3=he1b5a44_1001
- olefile=0.46=py_0
- pcre=8.43=he1b5a44_0
- pillow=5.3.0=py37h00a061d_1000
- pixman=0.38.0=h516909a_1003
- pthread-stubs=0.4=h14c3975_1001
- pycairo=1.18.2=py37h438ddbb_0
- rdkit=2019.09.2=py37hb31dc5d_0
- xorg-kbproto=1.0.7=h14c3975_1002
- xorg-libice=1.0.10=h516909a_0
- xorg-libsm=1.2.3=h84519dc_1000
- xorg-libx11=1.6.9=h516909a_0
- xorg-libxau=1.0.9=h14c3975_0
- xorg-libxdmcp=1.1.3=h516909a_0
- xorg-libxext=1.3.4=h516909a_0
- xorg-libxrender=0.9.10=h516909a_1002
- xorg-renderproto=0.11.1=h14c3975_1002
- xorg-xextproto=7.3.0=h14c3975_1002
- xorg-xproto=7.0.31=h14c3975_1007
- zstd=1.4.4=h3b9ef0a_1
- _libgcc_mutex=0.1=main
- blas=1.0=mkl
- ca-certificates=2019.11.27=0
- certifi=2019.11.28=py37_0
- cffi=1.13.2=py37h2e261b9_0
- click=7.0=py_0
- flask=1.1.1=py_0
- gevent=1.4.0=py37h7b6447c_0
- greenlet=0.4.15=py37h7b6447c_0
- intel-openmp=2019.4=243
- itsdangerous=1.1.0=py_0
- jinja2=2.10.3=py_0
- joblib=0.14.1=py_0
- libedit=3.1.20181209=hc058e9b_0
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=9.1.0=hdf63c60_0
- libgfortran-ng=7.3.0=hdf63c60_0
- libstdcxx-ng=9.1.0=hdf63c60_0
- lightgbm=2.3.0=py37he6710b0_0
- markupsafe=1.1.1=py37h7b6447c_0
- mkl=2019.4=243
- mkl-service=2.3.0=py37he904b0f_0
- mkl_fft=1.0.15=py37ha843d7b_0
- mkl_random=1.1.0=py37hd6b4f25_0
- ncurses=6.1=he6710b0_1
- numpy=1.17.4=py37hc1035e2_0
- numpy-base=1.17.4=py37hde5b4d6_0
- openssl=1.1.1d=h7b6447c_3
- pandas=0.25.3=py37he6710b0_0
- pip=19.3.1=py37_0
- pycparser=2.19=py_0
- python=3.7.5=h0371630_0
- python-dateutil=2.8.1=py_0
- pytz=2019.3=py_0
- readline=7.0=h7b6447c_5
- scikit-learn=0.22=py37hd81dba3_0
- scipy=1.3.2=py37h7c811a0_0
- setuptools=42.0.2=py37_0
- six=1.13.0=py37_0
- sqlite=3.30.1=h7b6447c_0
- tk=8.6.8=hbc83047_0
- werkzeug=0.16.0=py_0
- wheel=0.33.6=py37_0
- xz=5.2.4=h14c3975_4
- zlib=1.2.11=h7b6447c_3
